#!/usr/bin/env python3
"""
AegisOS — Calamares settings fix.
Replaces /etc/calamares/settings.conf with a config that uses only the
stock Calamares modules shipped by Ubuntu's calamares package.

Run with:  sudo python3 /tmp/fix-calamares-modules.py
Then:      sudo calamares
"""
import os, shutil, glob

# 1. Discover what stock modules actually exist on this system.
mod_dir = "/usr/lib/x86_64-linux-gnu/calamares/modules"
if not os.path.isdir(mod_dir):
    # Fallback to other common locations
    for cand in ["/usr/lib/calamares/modules", "/usr/lib64/calamares/modules"]:
        if os.path.isdir(cand):
            mod_dir = cand
            break

available = set(os.listdir(mod_dir)) if os.path.isdir(mod_dir) else set()
print(f"Found {len(available)} stock Calamares modules in {mod_dir}")
for m in sorted(available):
    print(f"  - {m}")
print()

# 2. Pick the SHOW sequence (UI pages) — keep only ones that exist
desired_show = ["welcome", "locale", "keyboard", "partition", "users", "summary"]
show_seq    = [m for m in desired_show if m in available]

# 3. Pick the EXEC sequence (actual install steps) — same filter
desired_exec = [
    "partition", "mount", "unpackfs", "machineid", "fstab", "locale",
    "keyboard", "localecfg", "users", "displaymanager", "networkcfg",
    "hwclock", "services-systemd", "bootloader-config", "grubcfg",
    "bootloader", "packages", "luksbootkeyfile", "luksopenswaphookcfg",
    "plymouthcfg", "initramfscfg", "initramfs", "removeuser",
    "umount",
]
exec_seq    = [m for m in desired_exec if m in available]

# 4. Final SHOW page
desired_done = ["finished"]
done_seq    = [m for m in desired_done if m in available]

print(f"Show pages   : {show_seq}")
print(f"Exec steps   : {exec_seq}")
print(f"Done page    : {done_seq}")
print()

# 5. Backup existing settings.conf
src = "/etc/calamares/settings.conf"
if os.path.exists(src):
    bak = f"{src}.aegisos-backup"
    shutil.copy2(src, bak)
    print(f"Backed up old settings.conf → {bak}")

# 6. Write new settings.conf
def yaml_list(items, indent="    "):
    return "\n".join(f"{indent}- {m}" for m in items)

content = f"""---
# AegisOS Calamares settings — uses only stock Ubuntu modules.
# Regenerated by fix-calamares-modules.py

modules-search: [ local, {mod_dir} ]

instances:

sequence:
- show:
{yaml_list(show_seq)}
- exec:
{yaml_list(exec_seq)}
- show:
{yaml_list(done_seq)}

branding: aegisos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
"""

with open(src, "w") as f:
    f.write(content)
print(f"Wrote new {src}")
print()

# 7. Write unpackfs.conf — points the installer at OUR squashfs.
# It will copy this squashfs onto the target disk during install.
unpack_conf = "/etc/calamares/modules/unpackfs.conf"
os.makedirs(os.path.dirname(unpack_conf), exist_ok=True)

# Pick whichever squashfs actually exists (cdrom mount point varies)
candidates = [
    "/cdrom/casper/minimal.standard.live.squashfs",
    "/cdrom/casper/filesystem.squashfs",
    "/run/live/medium/casper/minimal.standard.live.squashfs",
    "/run/live/medium/casper/filesystem.squashfs",
]
squashfs = next((p for p in candidates if os.path.exists(p)), candidates[0])
print(f"unpackfs source → {squashfs}")

with open(unpack_conf, "w") as f:
    f.write(f"""---
unpack:
    -   source: "{squashfs}"
        sourcefs: "squashfs"
        destination: ""
""")
print(f"Wrote {unpack_conf}")
print()

# 8. Quick sanity-check the branding.desc isn't missing any image files
bdesc = "/etc/calamares/branding/aegisos/branding.desc"
if os.path.exists(bdesc):
    import re
    with open(bdesc) as f:
        txt = f.read()
    refs = re.findall(r'["\']?(\w[\w\-]*\.png)["\']?', txt)
    bdir = os.path.dirname(bdesc)
    missing = [r for r in set(refs) if not os.path.exists(f"{bdir}/{r}")]
    if missing:
        print(f"WARN: branding.desc references missing images: {missing}")
        print(f"      Run fix-calamares.py again to regenerate them.")
    else:
        print(f"branding.desc image references — all present.")
else:
    print("Note: /etc/calamares/branding/aegisos/branding.desc not found — that's OK.")

print()
print("Done. Now run:  sudo calamares")
